events {}

http {
    upstream opcos_nodes {
        server opc-os:8000 max_fails=3 fail_timeout=10s;
        server opc-os-secondary:8000 max_fails=3 fail_timeout=10s backup;
    }

    server {
        listen 8080;

        location /health {
            proxy_pass http://opcos_nodes/health;
        }

        location / {
            proxy_pass http://opcos_nodes;
        }
    }
}
